apiVersion: batch/v1beta1 
kind: CronJob 
metadata: 
  name: duplexjob2
spec: 
  schedule: "*/1 * * * *" 
  concurrencyPolicy: Forbid 
  jobTemplate: 
    spec: 
      template:
        spec: 
          containers: 
          - name: duplexjobtest 
            image: centos:latest 
            command: ["sleep"] 
            args: ["600"] 
          restartPolicy: Never 
